application: elastic-solutions
runtime: python27
api_version: 1
threadsafe: yes
version: 4

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: elaapp/static
  
- url: /_ah/(mapreduce|queue|warmup).*
  script: elapp.wsgi.application
  login: admin
  
- url: .*
  script: elasite.wsgi.application
  
  

libraries:
- name: MySQLdb
  version: 1.2.5
- name: django
  version: 1.5

  
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'elasite.settings'
